title: 3355
email: kmjnwon@gmail.com
baseurl: ""
url: ""
permalink: /:categories/:title/

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"